version: "3.7" 
services:
    idp.db:
        image: mysql:8.0.19
        container_name: idp-mysql
        environment:
            # change root password -> Change it before loading DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: H2020.IPMDecisions.IDP
        volumes:
            - dbdata:/var/lib/mysql
            - ./MySQL_Init_Script:/docker-entrypoint-initdb.d
        restart: always
        networks:
            idp_network:
                ipv4_address: 172.18.1.6
    phpmyadmin:
        depends_on:
        - idp.db
        image: phpmyadmin/phpmyadmin
        container_name: ipmdecisions.idp.phpmyadmin
        restart: always
        ports:
            - '9080:80'
        environment:
            PMA_HOST: idp.db
        networks:
            idp_network:
                ipv4_address: 172.18.1.7
    idp.api:
        depends_on:
            - idp.db
        image: ipmdecisions/identityproviderservice:latest
        container_name: idp-api
        hostname: idp.api
        restart: always
        ports:
            - "80:80" 
            - "443:443"
        build:
            context: ../
            dockerfile: ./Docker/Dockerfile
            args:
                BUILDER_VERSION: latest
                RELEASE_DATE: "2020-03-03"
        environment:
            # The following db username and password are create in line 32 in the MySQL_Init_Script/init.sql -> Change them before loading DB
            - ConnectionStrings:MySqlDbConnection=Server=idpdb;Database=H2020.IPMDecisions.IDP;Uid=ipm_idp_user;Pwd=user_password;
            - JwtSettings:TokenLifetimeMinutes=80
            - JwtSettings:SecretKey=AddYourSecretKey
            - JwtSettings:IssuerServerUrl=AddYourServer
            # The following Audience URL is in line 56 in the MySQL_Init_Script/init.sql
            - JwtSettings:ValidAudiencesUrls=https://testclient.com
            - AllowedHosts=*
            - ASPNETCORE_ENVIRONMENT=Development # Development, Staging or Production. Production enforces HTTPS, so only use when certificates installed
            - ASPNETCORE_URLS=http://+:80            
            # Comment line above and uncomment the following 4 lines once you have a valid certificate
            # - ASPNETCORE_URLS=https://+:443;http://+:80
            # - ASPNETCORE_HTTPS_PORT=443
            # - ASPNETCORE_Kestrel__Certificates__Default__Password=YourCertificatePassword
            # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/YourCertificate.pfx
        # volumes: 
        #     - ~/.aspnet/https:/https:ro # Path certificate in Host machine
        networks:
            idp_network:
                ipv4_address: 172.18.1.5
networks:
    idp_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.1.0/24
volumes:
    dbdata: