version: "3.7" 
services:
    idpdb:
        image: mysql:8.0.19
        container_name: ipmdecisions.idp.mysql
        environment:
            # change root password -> Change it before loading DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: H2020.IPMDecisions.IDP
        volumes:
            - dbdata:/var/lib/mysql
            - ./MySQL_Init_Script:/docker-entrypoint-initdb.d
        restart: always
        networks:
            idp_network:
                ipv4_address: 172.18.1.6
    phpmyadmin:
        depends_on:
        - idpdb
        image: phpmyadmin/phpmyadmin
        container_name: ipmdecisions.idp.phpmyadmin
        restart: always
        ports:
            - '9080:80'
        environment:
            PMA_HOST: idpdb
        networks:
            idp_network:
                ipv4_address: 172.18.1.7
    idp:
        depends_on:
            - idpdb
        image: ipmdecisions/identityproviderservice:latest
        container_name: ipmdecisions.idp.api
        user: root
        restart: always
        ports:
            - "8086:5000"
        build:
            context: ../
            dockerfile: ./Docker/Dockerfile
            args:
                BUILDER_VERSION: latest
                URL_PORT: 5000
                RELEASE_DATE: "2020-03-03"
        environment:
            # The following db username and password are create in line 32 in the MySQL_Init_Script/init.sql -> Change them before loading DB
            - ConnectionStrings:MySqlDbConnection=Server=idpdb;Database=H2020.IPMDecisions.IDP;Uid=ipm_idp_user;Pwd=user_password;
            - JwtSettings:TokenLifetimeMinutes=80
            - JwtSettings:SecretKey=AddYourSecretKey
            - JwtSettings:IssuerServerUrl=AddYourServer
            # The following Audience URL is in line 56 in the MySQL_Init_Script/init.sql
            - JwtSettings:ValidAudiencesUrls=https://testclient.com
            - AllowedHosts=*
            - IPMEmailMicroservice:ApiGatewayAddress=whereApiGatewayIsHosted
            - IPMEmailMicroservice:EmailMicroservice=api/eml/ 
            - IPMEmailMicroservice:SecurityTokenCustomHeader=ipm-eml-auth
            - IPMEmailMicroservice:SecurityToken=1234
            - NLog:targets:logfile:fileName=./logs/imp-decisions-IDP-${shortdate}.log
            - NLog:rules:logfile:minLevel=Info
        volumes:
            - logsvolume:/app/logs
        networks:
            idp_network:
                ipv4_address: 172.18.1.5              
    filebeat:
        image: docker.elastic.co/beats/filebeat:7.6.1
        container_name: filebeat
        restart: always
        user: root
        ports:
            - "8087:80"
        volumes:
            - logsvolume:/app/logs
            #Volume commented since command does not work on all systems. Manual cp required after docker compose run, refer to read me.
            #docker cp ./Docker/Filebeat/filebeat.yml filebeat:/usr/share/filebeat
            #- ./Filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        networks:
            idp_network:
                ipv4_address: 172.18.1.8
    elk:
        image: sebp/elk
        container_name: elkstack
        #Uncommenting may be of help on some systems
        #environment:
        #    - ES_CONNECT_RETRY=300
        restart: always
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        volumes:
            #Volume mounted so that log data persists between container restarts
            - elkvolume:/var/lib/elasticsearch
            #Volume commented since command does not work on all systems. Manual cp required after docker compose run, refer to read me.
            #docker cp ./Docker/ELK/logstash-conf/02-beats-input.conf  elkstack:/etc/logstash/conf.d/02-beats-input.conf
            #- ./ELK/logstash-conf/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf:ro
        networks:
            idp_network:
                ipv4_address: 172.18.1.9

networks:
    idp_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.1.0/24
volumes:
    dbdata:
    #Shared volume for log files
    logsvolume:
    #Volume for log files on ELK
    elkvolume:
