name: Build Docker Image And Push To Registry

on: [push]
  # push:
  #   tags:
  #     - 'v*.*.*'
env:
  IMAGE_NAME: h2020ipmdecisions/identityproviderservice
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build image with latest
      run: docker build . -f "./Docker/Dockerfile" -t "${{IMAGE_NAME}}:latest"
    - name: Build image with tag
      run: docker build . -f "./Docker/Dockerfile" -t "${{IMAGE_NAME}}:${{steps.vars.outputs.tag}}"
    # - name: Login to DockerHub Registry
    #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # - name: Set tag
    #   id: get_tag_name
    #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    # - name: Build and Push docker
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   env:
    #     URL_PORT: 5000
    #     BUILD_VERSION: 1.0.2
    #   with:
    #     name: h2020ipmdecisions/identityproviderservice
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     workdir: Docker
    #     dockerfile: Dockerfile
    #     context: H2020.IPMDecisions.IDP.API
    #     buildargs: URL_PORT,BUILD_VERSION
    #     tags: "latest"
