name: Build Docker Image And Push To Registry

on: [push]
  # push:
  #   tags:
  #     - 'v*.*.*'
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: h2020ipmdecisions/identityproviderservice
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build image
      run: |
        docker build --rm --pull -f ".\Docker\Dockerfile" -t "h2020ipmdecisions/identityproviderservice:latest" --build-arg URL_PORT=5000 --build-arg BUILDER_VERSION=0.0.2 .

    # - name: Set tag
    #   id: get_tag_name
    #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    # - name: Build and Push docker
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   env:
    #     URL_PORT: 5000
    #     BUILD_VERSION: 1.0.2
    #   with:
    #     name: h2020ipmdecisions/identityproviderservice
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     workdir: Docker
    #     dockerfile: Dockerfile
    #     context: H2020.IPMDecisions.IDP.API
    #     buildargs: URL_PORT,BUILD_VERSION
    #     tags: "latest"
